import asyncio
from typing import Any

from fastapi.testclient import TestClient

from app.ai import StructuredGenerationRequest, StructuredGenerationResponse
from app.main import app
from app.api import config as config_api
from app.api import generation as generation_api
from app.backends.databricks_backend import DatabricksGenerationBackend
from app.config import Settings
from app.models.base import BackendHealth
from app.models.generation import GeneratedSection, GenerationJobStatus, GenerateRequest, GenerationResult
from app.repositories.memory import case_repository
from app.services.extraction import ALL_FIELD_SPECS, source_processor


REAL_SOURCE_TEXT = b"""Clean Water Opportunity
Problem: Rural clinics face unreliable water systems that interrupt safe care.
Solution: Install solar-powered purification hubs with district maintenance teams.
Funding range: USD 12-18 million.
Diligence: funding recipient and investment vehicle are not yet defined.
"""


class FakeLiveBackend:
    async def health_check(self) -> BackendHealth:
        return BackendHealth(
            status="ok",
            provider="databricks-generation-backend",
            message="configured",
        )


class FakeStructuredProvider:
    def __init__(self) -> None:
        self.requests: list[StructuredGenerationRequest] = []

    def generate_structured(
        self,
        request: StructuredGenerationRequest,
    ) -> StructuredGenerationResponse:
        self.requests.append(request)
        if request.operation == "regenerate_draft_section":
            return StructuredGenerationResponse(
                output={
                    "id": "model-proposed-id",
                    "type": "narrative",
                    "heading": "Sharper Claude Section",
                    "body": "Regenerated by the Databricks Claude structured provider.",
                    "citations": [],
                },
                modelProvider="backend-databricks-model-serving",
                modelName="databricks-claude-opus-5",
                storedPayloadMode="validated_outputs_only",
                redactedResponseJson={"finishReasons": ["stop"]},
            )

        selected_outputs = request.input["caseBrief"]["selectedOutputs"]
        return StructuredGenerationResponse(
            output=self._generation_output(
                project_id=request.input["caseBrief"]["expectedProjectId"],
                generation_id=request.input["caseBrief"]["expectedGenerationId"],
                selected_outputs=selected_outputs,
            ),
            modelProvider="backend-databricks-model-serving",
            modelName="databricks-claude-opus-5",
            storedPayloadMode="validated_outputs_only",
            redactedResponseJson={"finishReasons": ["stop"]},
        )

    def _generation_output(
        self,
        *,
        project_id: str,
        generation_id: str,
        selected_outputs: list[str],
    ) -> dict[str, Any]:
        citation = {
            "sourceId": "src-vaccine-strategy",
            "label": "Vaccine Strategy 2026",
            "locator": "p. 2",
            "excerpt": "Synthetic strategy excerpt.",
        }
        return {
            "generationId": generation_id,
            "projectId": project_id,
            "status": "completed",
            "outputs": [
                {
                    "id": f"out-{output_type}",
                    "type": output_type,
                    "title": output_type.replace("_", " ").title(),
                    "status": "Model generated",
                    "sections": [
                        {
                            "id": f"{output_type}-summary",
                            "type": "narrative",
                            "heading": "Claude Draft",
                            "body": "Generated by Databricks Claude for the UI route.",
                            "citations": [citation],
                        }
                    ],
                }
                for output_type in selected_outputs
            ],
            "informationNeeded": [],
            "reviewFindings": [
                {
                    "id": "finding-human-review",
                    "severity": "blocking",
                    "type": "human_review",
                    "message": "Human review is required before external use.",
                    "resolved": False,
                }
            ],
            "metadata": {
                "storedPayloadMode": "validated_outputs_only",
                "modelProvider": "backend-databricks-model-serving",
            },
        }


class TalkingPointsOmittingProvider(FakeStructuredProvider):
    def _generation_output(
        self,
        *,
        project_id: str,
        generation_id: str,
        selected_outputs: list[str],
    ) -> dict[str, Any]:
        output = super()._generation_output(
            project_id=project_id,
            generation_id=generation_id,
            selected_outputs=selected_outputs,
        )
        output["outputs"] = [
            item
            for item in output["outputs"]
            if item["type"] != "talking_points"
        ]
        return output


class FakeExtractionProvider:
    def generate_structured(
        self,
        request: StructuredGenerationRequest,
    ) -> StructuredGenerationResponse:
        fields = []
        for spec in ALL_FIELD_SPECS:
            if spec.field_id == "opportunity_name":
                fields.append(
                    {
                        "id": spec.field_id,
                        "value": "Clean Water Opportunity",
                        "confidence": 0.94,
                        "evidenceStatus": "source_provided",
                        "pageNumber": 1,
                        "excerpt": "Clean Water Opportunity",
                    }
                )
            elif spec.field_id == "funding_range":
                fields.append(
                    {
                        "id": spec.field_id,
                        "value": "USD 12-18 million.",
                        "confidence": 0.9,
                        "evidenceStatus": "source_provided",
                        "pageNumber": 1,
                        "excerpt": "Funding range: USD 12-18 million.",
                    }
                )
            else:
                fields.append(
                    {
                        "id": spec.field_id,
                        "value": spec.unresolved,
                        "confidence": 0.3,
                        "evidenceStatus": "unresolved",
                        "pageNumber": None,
                        "excerpt": "",
                    }
                )
        return StructuredGenerationResponse(
            output={
                "selectedOpportunity": "Clean Water Opportunity",
                "selectionRationale": "Fake extraction for generation mapping.",
                "notes": "",
                "fields": fields,
            },
            modelProvider="fake-extraction-provider",
            modelName="fake-extraction-model",
            storedPayloadMode="validated_outputs_only",
            redactedResponseJson={"finishReasons": ["stop"]},
        )


class SlowGenerationBackend:
    def __init__(self) -> None:
        self.calls = 0
        self.started = asyncio.Event()
        self.release = asyncio.Event()

    async def health_check(self) -> BackendHealth:
        return BackendHealth(
            status="ok",
            provider="test-generation-backend",
            message="configured",
        )

    async def generate(self, project: Any) -> GenerationResult:
        self.calls += 1
        self.started.set()
        await self.release.wait()
        return GenerationResult(
            generationId=f"gen-{project.id}-shared",
            projectId=project.id,
            status="completed",
            outputs=[
                {
                    "id": "out-investment-case",
                    "type": "investment_case",
                    "title": "Investment Case Draft",
                    "status": "Model generated",
                    "sections": [
                        {
                            "id": "case-summary",
                            "type": "narrative",
                            "heading": "Shared Draft",
                            "body": "Generated once for duplicate requests.",
                            "citations": [],
                        }
                    ],
                }
            ],
            informationNeeded=[],
            reviewFindings=[],
            metadata={"mode": "live"},
        )

    async def regenerate_section(self, project: Any, generation: Any, section_id: str) -> GeneratedSection:
        raise AssertionError("regenerate_section should not be called")


class FailingGenerationBackend(SlowGenerationBackend):
    async def generate(self, project: Any) -> GenerationResult:
        self.calls += 1
        self.started.set()
        raise ValueError("Synthetic backend failure.")


async def wait_for_terminal_generation_status(project_id: str) -> GenerationJobStatus:
    for _ in range(20):
        status = await generation_api.generation_status(project_id)
        if status.state in {"completed", "failed", "canceled"}:
            return status
        await asyncio.sleep(0)
    raise AssertionError("Generation did not reach a terminal status.")


def test_ui_generation_backend_calls_databricks_claude_provider() -> None:
    provider = FakeStructuredProvider()
    backend = DatabricksGenerationBackend(
        Settings(
            model_provider_mode="databricks",
            databricks_host="https://workspace.cloud.databricks.com",
            databricks_model_serving_endpoint="databricks-claude-opus-5",
            databricks_token="token-1",
        ),
        provider=provider,  # type: ignore[arg-type]
    )
    project = case_repository.get_project("demo-project-1")

    result = asyncio.run(backend.generate(project))

    assert provider.requests
    request = provider.requests[0]
    assert request.operation == "render_executive_investment_case"
    assert request.metadata == {
        "promptName": "generate-investment-case",
        "uiRoute": "/api/projects/{projectId}/generate",
    }
    assert result.project_id == project.id
    assert result.metadata["provider"] == "backend-databricks-model-serving"
    assert result.metadata["modelName"] == "databricks-claude-opus-5"
    assert result.metadata["generatedVia"] == "/api/projects/{projectId}/generate"
    assert all(output.status == "Model generated - human review required" for output in result.outputs)


def test_databricks_generation_backend_keeps_package_when_model_omits_selected_output() -> None:
    provider = TalkingPointsOmittingProvider()
    backend = DatabricksGenerationBackend(
        Settings(
            model_provider_mode="databricks",
            databricks_host="https://workspace.cloud.databricks.com",
            databricks_model_serving_endpoint="databricks-claude-opus-5",
            databricks_token="token-1",
        ),
        provider=provider,  # type: ignore[arg-type]
    )
    project = case_repository.get_project("demo-project-1")

    result = asyncio.run(backend.generate(project))

    assert result.status == "needs_information"
    assert [output.type for output in result.outputs] == [
        "investment_case",
        "one_page",
        "talking_points",
        "source_appendix",
    ]
    talking_points = result.outputs[2]
    assert talking_points.status == "Not generated by model - human review required"
    assert "did not include the selected Meeting Talking Points output" in talking_points.sections[0].body
    assert result.metadata["omittedSelectedOutputTypes"] == "talking_points"
    assert any(item.id == "missing-output-talking_points" for item in result.information_needed)
    assert any(
        finding.type == "model_omitted_selected_output"
        and "Meeting Talking Points" in finding.message
        for finding in result.review_findings
    )


def test_databricks_generation_request_includes_ui_setup_and_uploaded_source(monkeypatch) -> None:
    monkeypatch.setattr(source_processor, "_provider_factory", lambda: FakeExtractionProvider())
    test_client = TestClient(app)
    provider = FakeStructuredProvider()
    backend = DatabricksGenerationBackend(
        Settings(
            model_provider_mode="databricks",
            databricks_host="https://workspace.cloud.databricks.com",
            databricks_model_serving_endpoint="databricks-claude-opus-5",
            databricks_token="token-1",
        ),
        provider=provider,  # type: ignore[arg-type]
    )
    project = test_client.post("/api/projects", json={"name": "Model request mapping"}).json()
    project_id = project["id"]
    audience = test_client.get("/api/audiences").json()[0]
    test_client.put(
        f"/api/projects/{project_id}/opportunity-audience",
        json={
            "sourceMode": "new",
            "opportunityId": None,
            "audienceId": audience["id"],
            "intendedOutcome": "Explore a co-funding partnership",
            "suggestions": [],
            "selectedOutputs": ["investment_case", "source_appendix"],
        },
    )
    extraction = test_client.post(
        f"/api/sources/extract?projectId={project_id}&filename=clean-water.txt",
        content=REAL_SOURCE_TEXT,
        headers={"content-type": "text/plain"},
    ).json()
    for field in extraction["fields"]:
        field["verified"] = True
    test_client.put(
        f"/api/projects/{project_id}/extraction-review",
        json={"fields": extraction["fields"], "confirmed": True},
    )
    project_model = case_repository.get_project(project_id)

    result = asyncio.run(backend.generate(project_model))

    request = provider.requests[-1]
    payload = request.input
    assert result.metadata["mode"] == "live"
    assert payload["caseBrief"]["selectedAudience"]["id"] == audience["id"]
    assert payload["caseBrief"]["project"]["reviewSetup"]["approachFields"]
    assert payload["caseBrief"]["selectedOutputs"] == ["investment_case", "source_appendix"]
    assert any(fact["id"] == "funding_range" and "USD 12-18 million" in fact["value"] for fact in payload["approvedFactLedger"])
    assert any(excerpt["label"] == "clean-water.txt" for excerpt in payload["sourceExcerpts"])
    assert any(field["id"] == "funding_range" for field in payload["extractedFields"])


def test_databricks_section_regeneration_uses_claude_provider() -> None:
    provider = FakeStructuredProvider()
    backend = DatabricksGenerationBackend(
        Settings(
            model_provider_mode="databricks",
            databricks_host="https://workspace.cloud.databricks.com",
            databricks_model_serving_endpoint="databricks-claude-opus-5",
            databricks_token="token-1",
        ),
        provider=provider,  # type: ignore[arg-type]
    )
    project = case_repository.get_project("demo-project-1")
    generation = GenerationResult(
        generationId="gen-demo-project-1",
        projectId=project.id,
        status="completed",
        outputs=[
            {
                "id": "out-investment-case",
                "type": "investment_case",
                "title": "Investment Case Draft",
                "status": "Model generated - human review required",
                "sections": [
                    GeneratedSection(
                        id="case-summary",
                        type="risk",
                        heading="Existing Section",
                        body="Existing body.",
                        citations=[],
                    )
                ],
            }
        ],
        informationNeeded=[],
        reviewFindings=[],
        metadata={"storedPayloadMode": "validated_outputs_only"},
    )

    section = asyncio.run(
        backend.regenerate_section(project, generation, "case-summary"),
    )

    assert provider.requests[-1].operation == "regenerate_draft_section"
    assert section.id == "case-summary"
    assert section.type == "risk"
    assert section.heading == "Sharper Claude Section"


def test_config_reports_live_mode_for_databricks_backend(monkeypatch) -> None:  # type: ignore[no-untyped-def]
    monkeypatch.setattr(
        config_api,
        "get_generation_backend",
        lambda: FakeLiveBackend(),
    )

    payload = asyncio.run(config_api.get_config())

    assert payload["mode"] == "live"
    assert payload["backend"]["provider"] == "databricks-generation-backend"


def test_duplicate_project_generation_requests_share_one_backend_task(monkeypatch) -> None:  # type: ignore[no-untyped-def]
    test_client = TestClient(app)
    project = test_client.post("/api/projects", json={"name": "Duplicate generation"}).json()
    project_id = project["id"]
    backend = SlowGenerationBackend()
    monkeypatch.setattr(generation_api, "get_generation_backend", lambda: backend)

    async def run_duplicate_requests() -> tuple[GenerationJobStatus, GenerationJobStatus, GenerationJobStatus]:
        first_result = await generation_api.generate(project_id, GenerateRequest(simulateError=False))
        await backend.started.wait()
        second_result = await generation_api.generate(project_id, GenerateRequest(simulateError=False))
        backend.release.set()
        completed_result = await wait_for_terminal_generation_status(project_id)
        saved_result = await generation_api.generate(project_id, GenerateRequest(simulateError=False))
        assert completed_result.state == "completed"
        return first_result, second_result, saved_result

    first_result, second_result, saved_result = asyncio.run(run_duplicate_requests())

    assert backend.calls == 1
    assert first_result.state == "running"
    assert second_result.state == "running"
    assert saved_result.state == "completed"
    assert saved_result.result is not None
    assert saved_result.generation_id == f"gen-{project_id}-shared"
    assert saved_result.result.generation_id == saved_result.generation_id


def test_project_generation_can_be_canceled_and_retried(monkeypatch) -> None:  # type: ignore[no-untyped-def]
    test_client = TestClient(app)
    project = test_client.post("/api/projects", json={"name": "Cancelable generation"}).json()
    project_id = project["id"]
    backend = SlowGenerationBackend()
    monkeypatch.setattr(generation_api, "get_generation_backend", lambda: backend)

    async def cancel_and_retry() -> tuple[
        GenerationJobStatus,
        GenerationJobStatus,
        GenerationJobStatus,
        GenerationJobStatus,
        GenerationJobStatus,
    ]:
        start_status = await generation_api.generate(project_id, GenerateRequest(simulateError=False))
        await backend.started.wait()
        cancel_status = await generation_api.cancel_generation(project_id)
        status_after_cancel = await generation_api.generation_status(project_id)
        retry_status = await generation_api.generate(project_id, GenerateRequest(simulateError=False))
        backend.release.set()
        completed_status = await wait_for_terminal_generation_status(project_id)
        return start_status, cancel_status, status_after_cancel, retry_status, completed_status

    start_status, cancel_status, status_after_cancel, retry_status, completed_status = asyncio.run(cancel_and_retry())

    assert start_status.state == "running"
    assert cancel_status.state == "canceled"
    assert cancel_status.error is None
    assert "No output package was saved" in cancel_status.message
    assert status_after_cancel.state == "canceled"
    assert retry_status.state == "running"
    assert completed_status.state == "completed"
    assert completed_status.generation_id == f"gen-{project_id}-shared"
    assert backend.calls == 2


def test_generation_status_reports_background_backend_failure(monkeypatch) -> None:  # type: ignore[no-untyped-def]
    test_client = TestClient(app)
    project = test_client.post("/api/projects", json={"name": "Failed background generation"}).json()
    project_id = project["id"]
    backend = FailingGenerationBackend()
    monkeypatch.setattr(generation_api, "get_generation_backend", lambda: backend)

    async def fail_generation() -> tuple[GenerationJobStatus, GenerationJobStatus]:
        start_status = await generation_api.generate(project_id, GenerateRequest(simulateError=False))
        await backend.started.wait()
        terminal_status = await wait_for_terminal_generation_status(project_id)
        return start_status, terminal_status

    start_status, terminal_status = asyncio.run(fail_generation())

    assert backend.calls == 1
    assert start_status.state == "running"
    assert terminal_status.state == "failed"
    assert terminal_status.error is not None
    assert "Synthetic backend failure" in terminal_status.error
