import asyncio
from typing import Any

from fastapi.testclient import TestClient

from app.ai import StructuredGenerationRequest, StructuredGenerationResponse
from app.main import app
from app.api import config as config_api
from app.backends.databricks_backend import DatabricksGenerationBackend
from app.config import Settings
from app.models.base import BackendHealth
from app.models.generation import GeneratedSection, GenerationResult
from app.repositories.memory import case_repository


REAL_SOURCE_TEXT = b"""Clean Water Opportunity
Problem: Rural clinics face unreliable water systems that interrupt safe care.
Solution: Install solar-powered purification hubs with district maintenance teams.
Funding range: USD 12-18 million.
Diligence: funding recipient and investment vehicle are not yet defined.
"""


class FakeLiveBackend:
    async def health_check(self) -> BackendHealth:
        return BackendHealth(
            status="ok",
            provider="databricks-generation-backend",
            message="configured",
        )


class FakeStructuredProvider:
    def __init__(self) -> None:
        self.requests: list[StructuredGenerationRequest] = []

    def generate_structured(
        self,
        request: StructuredGenerationRequest,
    ) -> StructuredGenerationResponse:
        self.requests.append(request)
        if request.operation == "regenerate_draft_section":
            return StructuredGenerationResponse(
                output={
                    "id": "model-proposed-id",
                    "type": "narrative",
                    "heading": "Sharper Claude Section",
                    "body": "Regenerated by the Databricks Claude structured provider.",
                    "citations": [],
                },
                modelProvider="backend-databricks-model-serving",
                modelName="databricks-claude-opus-5",
                storedPayloadMode="validated_outputs_only",
                redactedResponseJson={"finishReasons": ["stop"]},
            )

        selected_outputs = request.input["caseBrief"]["selectedOutputs"]
        return StructuredGenerationResponse(
            output=self._generation_output(
                project_id=request.input["caseBrief"]["expectedProjectId"],
                generation_id=request.input["caseBrief"]["expectedGenerationId"],
                selected_outputs=selected_outputs,
            ),
            modelProvider="backend-databricks-model-serving",
            modelName="databricks-claude-opus-5",
            storedPayloadMode="validated_outputs_only",
            redactedResponseJson={"finishReasons": ["stop"]},
        )

    def _generation_output(
        self,
        *,
        project_id: str,
        generation_id: str,
        selected_outputs: list[str],
    ) -> dict[str, Any]:
        citation = {
            "sourceId": "src-vaccine-strategy",
            "label": "Vaccine Strategy 2026",
            "locator": "p. 2",
            "excerpt": "Synthetic strategy excerpt.",
        }
        return {
            "generationId": generation_id,
            "projectId": project_id,
            "status": "completed",
            "outputs": [
                {
                    "id": f"out-{output_type}",
                    "type": output_type,
                    "title": output_type.replace("_", " ").title(),
                    "status": "Model generated",
                    "sections": [
                        {
                            "id": f"{output_type}-summary",
                            "type": "narrative",
                            "heading": "Claude Draft",
                            "body": "Generated by Databricks Claude for the UI route.",
                            "citations": [citation],
                        }
                    ],
                }
                for output_type in selected_outputs
            ],
            "informationNeeded": [],
            "reviewFindings": [
                {
                    "id": "finding-human-review",
                    "severity": "blocking",
                    "type": "human_review",
                    "message": "Human review is required before external use.",
                    "resolved": False,
                }
            ],
            "metadata": {
                "storedPayloadMode": "validated_outputs_only",
                "modelProvider": "backend-databricks-model-serving",
            },
        }


def test_ui_generation_backend_calls_databricks_claude_provider() -> None:
    provider = FakeStructuredProvider()
    backend = DatabricksGenerationBackend(
        Settings(
            model_provider_mode="databricks",
            databricks_host="https://workspace.cloud.databricks.com",
            databricks_model_serving_endpoint="databricks-claude-opus-5",
            databricks_token="token-1",
        ),
        provider=provider,  # type: ignore[arg-type]
    )
    project = case_repository.get_project("demo-project-1")

    result = asyncio.run(backend.generate(project))

    assert provider.requests
    request = provider.requests[0]
    assert request.operation == "render_executive_investment_case"
    assert request.metadata == {
        "promptName": "generate-investment-case",
        "uiRoute": "/api/projects/{projectId}/generate",
    }
    assert result.project_id == project.id
    assert result.metadata["provider"] == "backend-databricks-model-serving"
    assert result.metadata["modelName"] == "databricks-claude-opus-5"
    assert result.metadata["generatedVia"] == "/api/projects/{projectId}/generate"
    assert all(output.status == "Claude generated - human review required" for output in result.outputs)


def test_databricks_generation_request_includes_ui_setup_and_uploaded_source() -> None:
    test_client = TestClient(app)
    provider = FakeStructuredProvider()
    backend = DatabricksGenerationBackend(
        Settings(
            model_provider_mode="databricks",
            databricks_host="https://workspace.cloud.databricks.com",
            databricks_model_serving_endpoint="databricks-claude-opus-5",
            databricks_token="token-1",
        ),
        provider=provider,  # type: ignore[arg-type]
    )
    project = test_client.post("/api/projects", json={"name": "Model request mapping"}).json()
    project_id = project["id"]
    audience = test_client.get("/api/audiences").json()[0]
    test_client.put(
        f"/api/projects/{project_id}/opportunity-audience",
        json={
            "sourceMode": "new",
            "opportunityId": None,
            "audienceId": audience["id"],
            "intendedOutcome": "Explore a co-funding partnership",
            "suggestions": [],
            "selectedOutputs": ["investment_case", "source_appendix"],
        },
    )
    extraction = test_client.post(
        f"/api/sources/extract?projectId={project_id}&filename=clean-water.txt",
        content=REAL_SOURCE_TEXT,
        headers={"content-type": "text/plain"},
    ).json()
    for field in extraction["fields"]:
        field["verified"] = True
    test_client.put(
        f"/api/projects/{project_id}/extraction-review",
        json={"fields": extraction["fields"], "confirmed": True},
    )
    project_model = case_repository.get_project(project_id)

    result = asyncio.run(backend.generate(project_model))

    request = provider.requests[-1]
    payload = request.input
    assert result.metadata["mode"] == "live"
    assert payload["caseBrief"]["selectedAudience"]["id"] == audience["id"]
    assert payload["caseBrief"]["project"]["reviewSetup"]["approachFields"]
    assert payload["caseBrief"]["selectedOutputs"] == ["investment_case", "source_appendix"]
    assert any(fact["id"] == "funding_range" and "USD 12-18 million" in fact["value"] for fact in payload["approvedFactLedger"])
    assert any(excerpt["label"] == "clean-water.txt" for excerpt in payload["sourceExcerpts"])
    assert any(field["id"] == "funding_range" for field in payload["extractedFields"])


def test_databricks_section_regeneration_uses_claude_provider() -> None:
    provider = FakeStructuredProvider()
    backend = DatabricksGenerationBackend(
        Settings(
            model_provider_mode="databricks",
            databricks_host="https://workspace.cloud.databricks.com",
            databricks_model_serving_endpoint="databricks-claude-opus-5",
            databricks_token="token-1",
        ),
        provider=provider,  # type: ignore[arg-type]
    )
    project = case_repository.get_project("demo-project-1")
    generation = GenerationResult(
        generationId="gen-demo-project-1",
        projectId=project.id,
        status="completed",
        outputs=[
            {
                "id": "out-investment-case",
                "type": "investment_case",
                "title": "Investment Case Draft",
                "status": "Claude generated - human review required",
                "sections": [
                    GeneratedSection(
                        id="case-summary",
                        type="risk",
                        heading="Existing Section",
                        body="Existing body.",
                        citations=[],
                    )
                ],
            }
        ],
        informationNeeded=[],
        reviewFindings=[],
        metadata={"storedPayloadMode": "validated_outputs_only"},
    )

    section = asyncio.run(
        backend.regenerate_section(project, generation, "case-summary"),
    )

    assert provider.requests[-1].operation == "regenerate_draft_section"
    assert section.id == "case-summary"
    assert section.type == "risk"
    assert section.heading == "Sharper Claude Section"


def test_config_reports_live_mode_for_databricks_backend(monkeypatch) -> None:  # type: ignore[no-untyped-def]
    monkeypatch.setattr(
        config_api,
        "get_generation_backend",
        lambda: FakeLiveBackend(),
    )

    payload = asyncio.run(config_api.get_config())

    assert payload["mode"] == "live"
    assert payload["backend"]["provider"] == "databricks-generation-backend"
